### ISSUE TITLE
How to build it by using llvm-rs

### ISSUE THREAD

**Issue by yjhmelody** [maekawatoshiki/rapidus#1]
I had following errors, but I'm a beginnger in llvm.
I search the `LLVM_SYS_60_PREFIX` in docs and set it as `/usr/lib/llvm-6.0/lib`. But it still reported the same error. How to solve it. And can you give me some advises to use llvm and llvm-rs?

![image](https://user-images.githubusercontent.com/16250688/45254202-fa4b9300-b3a6-11e8-897f-17ed393f779c.png)

**Comment by maekawatoshiki** [comment]
the easiest way is making a symbolic link to llvm-config-6.0 as llvm-config.

**Comment by yjhmelody** [comment]
How it works ?

**Comment by maekawatoshiki** [comment]
> How it works ?

what do you mean? run this command:
```sh
sudo ln -sf /usr/bin/llvm-config-6.0 /usr/bin/llvm-config
```

and the error will disappear.

**Comment by yjhmelody** [comment]
Yes, it works.

> what do you mean?

 But, how does it works? I mean why do such thing?

**Comment by maekawatoshiki** [comment]
Sorry, I don't know the detail.
But I think ``export LLVM_SYS_60_PREFIX=/usr/lib/llvm-6.0`` may also work.

**Comment by yjhmelody** [comment]
Oh, Thank you. `export LLVM_SYS_60_PREFIX=/usr/lib/llvm-6.0` does not really worked. Could you give some urls to me about the `llvm` and `llvm-rs` core doc. I'm confused because of too many docs.

**Comment by maekawatoshiki** [comment]
When it comes to llvm-rs, I'm sure that the official document is the best: https://tombebbington.github.io/llvm-rs/llvm/index.html

For llvm, https://llvm.org/docs/tutorial/ (learn how to use llvm through making a language) is good. If you face a problem of llvm, searching for it in an honest way is all we can do :( 
And reading the source code of a project using llvm is another good way.

**Comment by yjhmelody** [comment]
Thank you. I will try.
