### ISSUE TITLE
"This" and global object, and module.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#12]
This is complexed (and really weird) issue which happens only in non-strict mode, and I may not have understood completely.
And I think this is a problem of implementation, rather than a bug.
First of all, see the test code and result below.

```javascript
var a = 10
function func(){
    a = 3
    b = 5
    console.log(this.a, this.b) // in function object, this = global object
}
func()
console.log(this.a, this.b) // in module scope, this = {}
```
```
$ cargo run test.js
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/rapidus test.js`
3 5
3 5
$ node test.js
undefined 5
undefined undefined
```
In the latest ECMA spec, the value of ```this``` keyword is resolved in the running execution context, whenever it is referred.
http://www.ecma-international.org/ecma-262/9.0/index.html#sec-this-keyword

And in node.js, every program file read is an independent module, and executed in the scope of each module (even if there is only one file), not the global scope. The global scope exists outer of the module scope. On the other hand, in web browsers, the top-level scope is the global scope.
https://nodejs.org/api/modules.html#modules_the_module_scope

When the ```func```  function is invoked in ```func()``` manner, ```this``` is bound to the Global object inside of the function. (when caller does not exist, ```this``` refer to the Global object in non-strict mode and ```undefined``` in strict mode)
http://www.ecma-international.org/ecma-262/9.0/index.html#sec-ecmascript-function-objects-call-thisargument-argumentslist

In executing ```func``` function, ```a``` is a variable declared in the main module scope (not global scope) and ```b``` refers to a property of the Global object. Thus, ```this.a``` is evaluated as undefined, whereas ```this.b``` is 5.
http://www.ecma-international.org/ecma-262/9.0/index.html#sec-global-environment-records

In node.js, ```this``` in module scope seems to be bound to an empty object ("{ }") **which is not equal to the Global object.**
Thus, in the global scope, "this.a" is resolved as "{}.a", which value is undefined as shown in second console.log() output.

To access the Global object directly, node.js provides "global" property of the Global object, which refers to the Global object itself. This means global.global === global.
Therefore, ```global.b``` in the module scope, is evaluated as 5.

**Comment by maekawatoshiki** [comment]
``this`` in node.js is equal to ``module.exports``, therefore, ``this === module.exports```.

**Comment by maekawatoshiki** [comment]
I have to consider how rapidus deals with this problem.

**Comment by sisshiki1969** [comment]
I got it, thanks.
