### ISSUE TITLE
This statement is not necessary. (and wrong...)

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#14]
https://github.com/maekawatoshiki/rapidus/blob/7259edd496b9f0fe12228b0b61abd764aa4f80ef/src/builtins/array.rs#L58

builtin_function_with_obj_and_prototype() do this the right way instead.

**Comment by maekawatoshiki** [comment]
thank you for your report.

**Comment by maekawatoshiki** [comment]
fixes
