### ISSUE TITLE
undefined is not a token

### ISSUE THREAD

**Issue by LuoZijun** [maekawatoshiki/rapidus#38]
CodeLine: https://github.com/maekawatoshiki/rapidus/blob/new-gen/src/parser.rs#L860

Ref: http://kangax.github.io/compat-table/es5/

Immutable globals:

* undefined
* NaN
* Infinity

So, the `undefined/NaN/Infinity` is just a global immutable property.

**Comment by maekawatoshiki** [comment]
Thank you for your  issue. I'll fix it soon.
