### ISSUE TITLE
comment which ends with multi-bytes unicode character followed by EOF causes panic.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#4]
probably due to improperly set **next_pos** in the second iter.next() of Lexer.skip_char(), when the first iter.next() returned EOF.

ex)
$ cat examples/test.js
console.log(1); // 異常$ cargo run examples/test.js
   Compiling rapidus v0.1.1 (~/Documents/GitHub/rapidus)
   Finished dev [unoptimized + debuginfo] target(s) in 6.17s
   Running `target/debug/rapidus examples/test.js`
thread 'main' panicked at 'byte index 23 is not a char boundary; it is inside '常' (bytes 22..25) of `console.log(1); // 異常`', libcore/str/mod.rs:2111:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'exited. status: 101', src/main.rs:104:25
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by maekawatoshiki** [comment]
Thank you for reporting. I'll fix it after Friday.

**Comment by maekawatoshiki** [comment]
Fixed
