### ISSUE TITLE
Parsing problem for an arrow function.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#40]
In ECMA spec, an [_ArrowFunction_](http://www.ecma-international.org/ecma-262/9.0/index.html#prod-ArrowFunction) is a variant of an [_AssignmentExpression_](http://www.ecma-international.org/ecma-262/9.0/index.html#prod-AssignmentExpression).
But in rapidus, an arrow function is parsed as a variant of a primary expression.
Thus, the parser can not detect a syntax error in such a code as follows.
```javascript
let i = 1 + (x) => x   // no error
let j = (x) => { return x } + 1   // no error
```

**Comment by maekawatoshiki** [comment]
Since https://github.com/maekawatoshiki/rapidus/commit/6092927c3b6e979cfb646f745cf68a5580e5c769, 
```js
let i = 1 + (x) => x   // no error
```
causes error.
The other one doesn't, though.

**Comment by maekawatoshiki** [comment]
Since https://github.com/maekawatoshiki/rapidus/commit/ae3ef536659533a1a4bba99e7fdb3d7f35b77454, all the examples you show cause syntax error.

**Comment by maekawatoshiki** [comment]
However my code looks so horrible. Do you have any idea to simplify my code?

**Comment by LuoZijun** [comment]
Maybe u can use my parser, but not finished yet:D

**Comment by maekawatoshiki** [comment]
@LuoZijun It seems I can get some hint from your code. Thank you.

**Comment by LuoZijun** [comment]
@maekawatoshiki 

It's not easy to implement a complete ECMAScript language parser, 
and there's too much work to do:)

**Comment by sisshiki1969** [comment]
The syntax of arrow function "(a, b, c) => {}" is very similar to that of _ParenthesizedExpression_ with comma operator "(a, b, c)", which is a variant of _PrimaryExpression_.
Thus, a backtracking in parser is inevitable.  I am trying to modify the lexer for backtracking.

https://tc39.github.io/ecma262/#prod-CoverParenthesizedExpressionAndArrowParameterList
https://tc39.github.io/ecma262/#prod-ArrowParameters
