### ISSUE TITLE
Suggestion: TypeScript support instead?

### ISSUE THREAD

**Issue by undefinedbuddy** [maekawatoshiki/rapidus#52]
I see that using ECMAScript's specification is exceedingly difficult. Would it sound more reasonable to use Rapidus for a strictly-typed version of TypeScript? Much like how strictly-typed TypeScript code can be compiled into a WASM module (except the WASM compilation part).

**Comment by LuoZijun** [comment]
@undefinedbuddy if you want compiled into a WASM module, why not use `Rust` ? :D

**Comment by undefinedbuddy** [comment]
The point of the suggestion wasn't to imply that I needed to compile TypeScript to WASM. Rather, I think it would be more meaningful if rapidus works with TypeScript (strictly checked preferred) than ECMAScript's standards.

Having a standard library based off dynamic libraries in Rust with a single build script to trigger cross-compilation of the core and built-in libraries would be sweet as well.

**Comment by maekawatoshiki** [comment]
TypeScript support is a great idea. I'll do it if I feel like it someday.

**Comment by undefinedbuddy** [comment]
Great. Looking forward to seeing that implemented!
