### ISSUE TITLE
parsing problem for post-increment(++) operator getting over line terminator

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#6]
The sequence of [_LeftHandSideExpression_][_LineTerminator_][++ or --] seems to be parsed wrong as [_Expression_][_++ or --_].

ex)
$ cat test.js
a = 1
b = a
++b  // parsed as "b = a; ++b;" in node, "b = a++; b;" in rapidus
console.log( a, b )
$ node test.js
1 2
$ cargo run test.js
2 1
$ cargo run  -- --debug test.js
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/rapidus --debug test.js`
Lexer:
Token { kind: Identifier("a"), pos: 0 }
Token { kind: Symbol(Assign), pos: 2 }
Token { kind: Number(1.0), pos: 4 }
Token { kind: Identifier("b"), pos: 6 }
Token { kind: Symbol(Assign), pos: 8 }
Token { kind: Identifier("a"), pos: 10 }
Token { kind: Symbol(Inc), pos: 13 }
Token { kind: Identifier("b"), pos: 15 }
Token { kind: Identifier("console"), pos: 80 }
Token { kind: Symbol(Point), pos: 87 }
Token { kind: Identifier("log"), pos: 88 }
Token { kind: Symbol(OpeningParen), pos: 91 }
Token { kind: Identifier("a"), pos: 93 }
Token { kind: Symbol(Comma), pos: 94 }
Token { kind: Identifier("b"), pos: 96 }
Token { kind: Symbol(ClosingParen), pos: 98 }
Parser:
Node { base: StatementList([Node { base: Assign(Node { base: Identifier("a"), pos: 0 }, Node { base: Number(1.0), pos: 4 }), pos: 1 }, Node { base: Assign(Node { base: Identifier("b"), pos: 6 }, Node { base: UnaryOp(Node { base: Identifier("a"), pos: 10 }, PoInc), pos: 11 }), pos: 7 }, Node { base: Identifier("b"), pos: 15 }, Node { base: Call(Node { base: Member(Node { base: Identifier("console"), pos: 80 }, "log"), pos: 87 }, [Node { base: Identifier("a"), pos: 93 }, Node { base: Identifier("b"), pos: 96 }]), pos: 87 }]), pos: 0 }

...

**Comment by maekawatoshiki** [comment]
It seems I didn't implement ASI correctly.
I'll fix it soon.

**Comment by maekawatoshiki** [comment]
This bug is fixed. However, ASI is not complete yet.

**Comment by sisshiki1969** [comment]
thanks!
ASI is really weird...
