### ISSUE TITLE
assignment expression does not return value.

### ISSUE THREAD

**Issue by sisshiki1969** [maekawatoshiki/rapidus#7]
assignment expression should return value (ex. 5 for "a=5") according to ECMA-262 spec.
In rapidus, example codes (listed below) are correctly parsed, but go panic while bytecode execution.
no value seems to push to VM.state.stack in VM.set_name() function.

ex)
console.log(a=5) 
a=b=5

**Comment by maekawatoshiki** [comment]
Hmm, It seems I completely don't know JS.
Appreciate your reporting.

**Comment by maekawatoshiki** [comment]
Fixed.

**Comment by sisshiki1969** [comment]
works fine!
thank you.
